name: KwikBandit
favicon: null
layout_spectrum: 0.42547
typography_spectrum: 0.57584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7aa9d9'
    - '#02080b'
    - '#feda00'
    - '#da9600'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
